---
title: "Glioma scRNA project - Loading data per sample"
author: "Youri Hoogstrate"
date: "`r BiocStyle::doc_date()`"
---

```{r, eval=FALSE}
remove.packages('SoupX')
xfun::install_github("https://github.com/yhoogstrate/SoupX/tree/passthrough_arguments")
```


# setup

```{r, message=F, warnings=F}
library(dplyr)

print(getwd()) # 

source('scripts/theme_youri.R')
```

# add sample desrciptors
```{r init df}
data_per_sample <- data.frame()
```

## van Hijfte - GBM sample Y

```{r attach dataset}
data_per_sample <- data_per_sample |> 
  rbind(data.frame(
    "sid" = "van_Hijfte_GBM_Y",
    "sample_name" = "van Hijfte - GBM Sample Y",
    "doi" = "https://dx.doi.org/zenodo.6546712",
    "path_seurat" = 'data/van_Hijfte_GBM_Y/Glioma_Y_and_O/Levi2_Glioma_Y/outs/raw_feature_bc_matrix'
  ))
```

# Add some columns based on existing

```{r}
data_per_sample <- data_per_sample |> 
  dplyr::mutate(path_soupx = gsub("^(.+)/[^.]+$","\\1", path_seurat)) |> 
  dplyr::mutate(n.barcodes = NA) |> 
  dplyr::mutate(n.genes = NA) |> 
  dplyr::mutate(n.reads = NA) |> 
  # cellranger csv
  dplyr::mutate(path_cellranger_summary = paste0(path_soupx, "/metrics_summary.csv"))|> 
  dplyr::mutate(tmp = read.csv(path_cellranger_summary)) |> 
  tidyr::unnest(tmp)
```



# Fig 1: Sample overview

```{r dataset overview}
data_per_sample
```

# obtain generic stats
## SoupX analysis

https://github.com/constantAmateur/SoupX

```{r}
sample <- data_per_sample |> 
  dplyr::slice(1)
```

```{r, message = FALSE, warning=FALSE}
sc <- SoupX::load10X(sample$path_soupx, verbose=T, keepDroplets=TRUE)
SoupX::plotDropletResolution(sc) +
  ggplot2::labs(subtitle = paste0("UMIs per droplot: ", sample$sample_name))
```


## obtain spike-ins

Spike-in virtual soup cells to show where they appear
```{r}
si <- SoupX::spikeInTheSoupChannel(sc,)
saveRDS(si, file=paste0("cache/soup-spike-ins/soup_spike_ins__",sample$sid,"__5000.Rds"))
rm(si)
```











































```{r}
sc <- SoupX::autoEstCont(sc)
out <- SoupX::adjustCounts(sc)
```

```{r, contribution genes to soup}
plt <- sc |>
  purrr::pluck('soupProfile') |> 
  dplyr::arrange(desc(est)) |> 
  tibble::rownames_to_column('gene_symbol') 

ggplot(plt |> head(n=20), aes(x=reorder(gene_symbol, desc(counts)), y=counts)) +
  geom_point() +
  scale_y_log10() +
  theme_youri_barplot
```

```{r}
SoupX::plotMarkerDistribution(sc)
```


```{r, eval=FALSE}
plotChangeMap(sc, out, "COL1A1")
plotChangeMap(sc, out, "COL1A2")
plotChangeMap(sc, out, "CD248")
plotChangeMap(sc, out, "PDGFRB")
plotChangeMap(sc, out, "CD163")
plotChangeMap(sc, out, "RBFOX3")
SoupX::plotMarkerMa
```


